apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volume-claim
# specifications of the resources needed from pod (attached to the pod) requested to k8s
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            # needs 2Gb of free space
            storage: 2Gi